package profile

const (
	PLATFORM_BIT = 12
	SERVER_BIT   = 9
	SYSTYPE_BIT  = 8
)

const (
	PAY_ORDER_STATUS_UNHANDLED = 0
	PAY_ORDER_STATUS_HANDLED   = 1
)
const (
	// USER_FLAG_POS_UIN          = 0
	USER_FLAG_POS_ACCOUNTID    = 1
	USER_FLAG_POS_ACCOUNTNAME  = 2
	USER_FLAG_POS_GENDER       = 3
	USER_FLAG_POS_PLATFORM     = 4
	USER_FLAG_POS_CHANNEL      = 5
	USER_FLAG_POS_SERVER       = 6
	USER_FLAG_POS_UUID         = 7
	USER_FLAG_POS_OS           = 8
	USER_FLAG_POS_OS_VERSION   = 9
	USER_FLAG_POS_DEVICE_MODEL = 10
	USER_FLAG_POS_CREATE_TIME  = 11
	USER_FLAG_POS_VIP          = 12
	USER_FLAG_POS_LEVEL        = 13
)
